---
title: "Untitled"
format: html
editor: visual
---

## Loading integrated data

```{r comparison}
abs1.df <- readxl::read_excel("data/ProQuestDocuments-2024-02-01.xls")
abs2.df <- readxl::read_excel("data/ProQuestDocuments-2024-02-01.2.xls")
diss_meta_cmp.df <- bind_rows(abs1.df, abs2.df)
rm(abs2.df,abs1.df)
```

```{r}
# retrieve and merge abstracts data
rawdir <- "data/raw"
mergedfile <- "data/diss_meta.RDS"

retrieve_raw_data <- function(dest) {
  requireNamespace("googledrive")
  folderid <- 'https://drive.google.com/drive/folders/1BFMQkwj24zwH3uTIFmrCnp32dkfY807E'
  
  filels <- googledrive::drive_ls(folderid)
 
  purrr::pwalk(filels, function(name,id,...) {
    googledrive::drive_download(
       file = id,
       path = file.path(dest,name),
      overwrite=TRUE)
    })
}

merge_raw_data<-function(dest) { 
   xls.ls <- dir(destdir,pattern="\\.xls", full.names = TRUE)
   ris.ls <- dir(destdir,pattern="\\.ris", full.names = TRUE)
   
   merged_xls.df <- purrr::map(xls.ls, readxl::read_excel) %>% 
     purrr::list_rbind()
   
   
   merged_ris.df <- purrr::map(ris.ls, revtools::read_bibliography) %>% 
     purrr::list_rbind()
   
   merged.df <- merged_xls.df %>% 
     left_join( merged_ris.df %>% select(advisor=author,StoreId=accession,
                      organization=publisher, place = "pubplace"),
                by = "StoreId" )
   
   merged.df
}

if (!file.exists(mergedfile)) {
  if (length(dir(destdir, pattern = "\\.ris$"))==0) {
      retrieve_raw_data(destdir)
  }
  diss_meta_full.df <- merge_raw_data(destdir)  
  saveRDS(diss_meta_full.df, file=mergedfile)
} 

diss_meta_full.df <- readRDS(mergedfile)
```

```{r}
## Notes:
# handlr - fails to read these bib files
# rbibutils - writes endnote, but reads only bibtex
# revutils - only reads default fields (and assumes a field mapping) -- but 
#          - works for the fields we are interested in, though needs remapping of
#          - some fields

requireNamespace("revutils")


merged_ris.df <- purrr::map(xls.ls, revutils::read_excel) %>% 
     purrr::list_rbind()




z <- system.file('extdata/crossref.ris', package = "handlr")
handlr::ris_reader(z)

z <- system.file('extdata/peerj.ris', package = "handlr")
ris_reader(z)

z <- system.file('extdata/plos.ris', package = "handlr")
ris_reader(z)

```
